### ISSUE TITLE
Allow localization or customization of the CPT slug (watched)

### ISSUE THREAD

**Issue by ronilaukkarinen** [jeherve/traktivity#180]
Thanks for the nice plugin! I did not find information on how to make the plugin work in my language. Also I'd like "watched" to be something else like "movies". What's the best way for translations and changing slugs?

**Comment by jeherve** [comment]
You should be able to suggest translations for all strings in your language here:
https://translate.wordpress.org/projects/wp-plugins/traktivity/

A translation editor will then have to go through your suggestions and validate them all, and they will then appear on your site as well as on all other sites using the plugin.
There is some more info about this here:
https://make.wordpress.org/polyglots/handbook/

To test strings before they've been approved by a validator, you can use this plugin:
https://wordpress.org/plugins/force-update-translations/

>  I'd like "watched" to be something else like "movies".

That's a bit more involved since that's something that's set when the Custom Post Type is declared.

Some translation plugins like Polylang or WPML give you that option, but that may be overkill if your site only uses one language.

It may be easier to fork my plugin and change the value here for now:
https://github.com/jeherve/traktivity/blob/a68c13ff597d36fa2b6019bfdfc0fd788ae4ef14/cpt.traktivity.php#L66

I'll leave this issue opened since that's definitely something I could make into an option in the future.

**Comment by ronilaukkarinen** [comment]
OK, thanks for this information, I'll look into it.

**Comment by jeherve** [comment]
I'm just releasing version 2.3.0 of the plugin, which introduces filters you can use to customize the slugs to fit your needs, like so:

```php
add_filter( 'traktivity_core_cpt_slug', function() { return 'some-unique-slug-of-your-choice'; } );
```

A word of warning though: once you change such a slug, you'll need to refresh all permalinks on your site. That can usually be done by going to Settings > Permalinks in your dashboard and clicking "Save Changes" at the bottom of the page. 
Obviously it's best to do so with a brand new site. Changing the slugs on a site that was already indexed by Google will cause some confusion for search engines since all the URLs will change.

Related commit with all the new filters: dbe17eab49e38807d2364713a57cbe371557e2af
